implement checkbox
iamsadafmhmdi/Splitwise pull request #7
Opened 2020-10-26 13:03 UTC by iamsadafmhmdi

2020-11-10 10:18 UTC, mehdibb requested changes

2020-11-10 10:18 UTC, mehdibb commented on index.js~HEAD
> +import {Button, Dialog, TextInput} from '../../components';
Same as the previous PR, this is unused variable too
```suggestion
import {Button, Dialog} from '../../components';
```

2020-11-10 10:18 UTC, mehdibb commented on src/components/Checkbox/index.css
> +.checkbox {
```suggestion
input[type=checkbox] {
```
instead of styling the check boxes using `classNames` you can do this

2020-11-10 10:18 UTC, mehdibb commented on src/components/Checkbox/index.css
> +.label{
```suggestion
label {
```
you're abusing the CSS `class names`

2020-11-10 10:18 UTC, mehdibb commented on src/components/Checkbox/index.js
> +            <label className='label'>
```suggestion
            <label>
```

2020-11-10 10:18 UTC, mehdibb commented on src/components/Checkbox/index.js
> +                    <input className='checkbox' type='checkbox' checked={checked} onChange={onChange} />
```suggestion
                    <input type='checkbox' checked={checked} onChange={onChange} />
```

2020-11-10 10:18 UTC, mehdibb commented on src/components/Checkbox/index.js
> +                {children}
this is weird since html checkbox doesn't support children, in fact no `input` tag supports it, instead of having a prop called `children` and using it as the label text you can name it as `label` and pass it as the children of the `label` tag
```suggestion
                {label}
```

2020-11-10 10:18 UTC, mehdibb commented on src/components/Checkbox/index.js
> +    children,
```suggestion
    label,
```

2020-11-10 10:18 UTC, mehdibb commented on src/components/TextInput/index.css
> +input {
here you've brought all of the code related to the `TextInput` PR to this PR which is wrong because of two reasons:

1. `TextInput` has its own PR
2. since the destination of both PRs is `master` the first one will be useless you make the destination of this one the `checbox` branch

2020-11-10 10:28 UTC, iamsadafmhmdi commented on src/components/TextInput/index.css
> +input {
you meant that I have to delete this PR and change the destination from master to checkbox? @mehdibb

2020-11-10 10:33 UTC, iamsadafmhmdi commented on src/components/TextInput/index.css
> +input {
I rebased text-Input to checkbox 
`(branch checkbox)$ git rebase text-input`
now you meant that I have to delete this PR ?

2020-11-14 20:49 UTC, mehdibb approved these changes

2020-11-14 20:57 UTC, mehdibb approved these changes

2020-11-14 20:57 UTC, merged